config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items do
    
    resources :favorites, only: [:create,:destroy]
    resources :comments, only: :create
    member do
      get 'confirm', to: 'items#confirm'
      post 'pay', to: 'items#pay'
      get 'done', to: 'items#done'
    end
    collection do
      get 'category_children'
      get 'category_grandchildren'
      get 'category'
    end
    collection do
      get 'search'
    end
  end
  resources :users, only: :show 
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :comments
  belongs_to :user, optional: true
  belongs_to :category, optional: true

  belongs_to_active_hash :prefecture, foreign_key: true
  belongs_to_active_hash :condition, foreign_key: true
  belongs_to_active_hash :deliverypays, foreign_key: true
  belongs_to_active_hash :deliverydate, foreign_key: true
  has_many :images, dependent: :destroy
  has_many :favorites
  has_many :users, through: :favorites
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name,    length: { in: 1..40 }
  validates :info,    length: { in: 1..1000 }
  validates :prefecture_id, numericality: { only_integer: true, greater_than: 0, less_than: 48 }
  validates :condition_id, numericality: { only_integer: true, greater_than: 0, less_than: 7 }
  validates :deliverypays_id, numericality: { only_integer: true, greater_than: 0, less_than: 3 }
  validates :deliverydate_id, numericality: { only_integer: true, greater_than: 0, less_than: 4 }
  validates :price, numericality: { only_integer: true, greater_than: 299, less_than: 10000000 }

  validates_associated :images
  validates :images, presence: true

  validates_associated :category
  validates :category_id, presence: true
  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:show, :confirm, :pay, :destroy, :done, :edit, :update]
  before_action :set_category, only: [new, :create]
  require 'payjp'

  def index
    @items = Item.order("created_at DESC")
    @images = Image.all
    @items = Item.all
    @categories = Category.all
    @parents = Category.where(ancestry: nil)
  end

  def show
    @grandchild = Category.find(@item.category_id)
    @child = @grandchild.parent
    @parent = @child.parent if @child
    @prefecture = Prefecture.find(@item.prefecture_id)
    @deliverydate = Deliverydate.find(@item.deliverydate_id)
    @deliverypays = Deliverypays.find(@item.deliverypays_id)
    @condition = Condition.find(@item.condition_id)
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def new
    @item = Item.new
    @item.images.new
    @items = Item.includes(:images).order('created_at DESC')
    @category = Category.roots
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to root_path
    else
      @category = Category.roots
      @item.images.new
      render :new
    end
      
  end

  def edit
    @category = Category.roots
    @grandchild_category = @item.category
    @child_category = @grandchild_category.parent
    @parent_category = @child_category.parent

    @category_parent_array = ["選択してください"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: @child_category.ancestry).each do |child|
      @category_children_array << child
    end

    @category_grandchildren_array = []
    Category.where(ancestry: @grandchild_category.ancestry).each do |grandchild|
      @category_grandchildren_array << grandchild
    end
  end


  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      @category = Category.roots
      render :edit
    end
  end

  def confirm
    @card = Card.where(user_id: current_user.id).first
    if @card.blank?
      redirect_to controller: "card", action: "new"
    else
      Payjp.api_key = Rails.application.credentials.PAYJP[:PAYJP_PRIVATE_KEY]
      
      customer = Payjp::Customer.retrieve(@card.customer_id)
      
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    @card = Card.where(user_id: current_user.id).first
    Payjp.api_key = Rails.application.credentials.PAYJP[:PAYJP_PRIVATE_KEY]
    Payjp::Charge.create(
    :amount => @item.price,
    :customer => @card.customer_id,
    :currency => 'jpy',
    )
    
    redirect_to action: 'done' 
  end

  def done
    @product_purchaser= Item.find(params[:id])
    @product_purchaser.update( buyer_id: current_user.id)
  end

  def destroy
    redirect_to root_path if @item.user_id == current_user.id && @item.destroy
  end

  def category_children
    @category_children = Category.find(params[:productcategory]).children
  end

  def category_grandchildren
    @category_grandchild = Category.find(params[:productcategory]).children
  end

  def category
    @items = Item.all
    @categories = Category.all
    @parents = Category.where(ancestry: nil)
  end

  def search
    @items = Item.search(params[:keyword]).order("created_at DESC").page(params[:page]).per(16)
  end

  private
  def item_params
    params.require(:item).permit(:name, :info, :category_id, :price, :condition_id, :deliverydate_id, :deliverypays_id, :brand, :prefecture_id, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
  
  def set_category
    @category = Category.all
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/category.html.haml
= render "more/header"


.parents-categories-top
  - @parents.each do |parent|
    .parents-category-top
      = link_to "#{parent.name}", { anchor: "#{parent.id}" }
- @parents.each do |parent|
  .children-categories-top
    .main-title-top{id: "#{parent.id}"}
      = link_to "#{parent.name}", id:"category-#{parent.id}"
    -parent.children.each do |child|
      .children-category-top
        .child-category-top
          .sub-title-top
            = link_to "#{child.name}"
        .grandchildren-categories-top
          -child.children.each do |grandchild|
            .grandchildren-category-top
              .grandchildren-title-top
                = link_to "#{grandchild.name}"
              


= render "more/footer"

app/views/items/confirm.html.haml
.o-contents
  = render "more/header"
  .b-main
    .b-items
      %h2.b-items__head
        購入内容の確認
      .b-items__buy-item
        .b-items__buy-item__box
          .b-items__buy-item__box--img
            = image_tag @item.images.first.src.url,size:"80x80"
          .b-items__buy-item__box--text
            .b-item-name
              = @item.name
            .b-item-price
              %span
                ¥
                = @item.price
              %span.b-item-price__fee
                (税込) 送料込み
      .b-buy-item
        .b-buy-item__inner
          .b-price-table
            .b-price-table__cell1
              支払い金額
            .b-price-table__cell2
              ¥
              = @item.price
          .b-buy-point
            .b-buy-point__box
            .b-buy-point__text
              ポイントを使用(所持ポイント:P0)
          .b-buy-content
            %h3
              支払い方法
            .b-buy-info
              .b-buy-info__text
                = link_to card_index_path do
                  - if @default_card_information.blank?
                    %br /
                  - else
                    = "**** **** **** " + @default_card_information.last4
                    - exp_month = @default_card_information.exp_month.to_s
                    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                    = exp_month + " / " + exp_year
          .b-user-info
            .b-user-info__text
              .b-user-info__text--left
                配送先
              %span.b-user-info__text--right
                = link_to "#" do
                  変更する
            .b-user-info__area
              %p
                〒000-0000
                %br
                xx県xx市xxxx
                %br
                名前
          = form_tag(pay_item_path, method: :post) do
            %button 購入する
  = render "more/footer"

app/views/items/done.html.haml
.done-main
  = render "more/header"
  .done-main__center
    .done-main__center__box
      .done-main__center__box__name
        = @item.name
      .done-main__center__box__title
        購入が完了しました！
      .done-main__center__box__top
        = link_to root_path do
          topページに戻る
= render "more/footer"

app/views/items/edit.html.haml
.is-whapper
  = render "more/header"
  = form_with model: @item, local: true do |form|
    - if @item.errors.any?
      .item__errors
        %h2= "#{@item.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @item.errors.full_messages.each do |message|
            %li= message
    .is-contents
      .sell-image-box
        .title
          .title__name
            出品画像
          .title__need
            必須
        .text
          最大10枚までアップロードできます
          #image-box
            #previews
              - if @item.persisted?
                - @item.images.each_with_index do |image, i|
                  = image_tag asset_path("#{image.src.url}"), data: {index: i}, width: "100", height: "100"
            
            = form.fields_for :images do |i|
              .js-file_group{data: {index: "#{i.index}"}, type: "file"}
                = i.file_field :src, class: "js-file"
                .js-file
                .js-remove 削除
              - if @item.persisted?
                = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
            - if @item.persisted?
              .js-file_group{"data-index" => "#{@item.images.count}"}
                = file_field_tag :src, name: "item[images_attributes][#{@item.images.count}][src]", class: 'js-file'
                .js-remove 削除
      .item-info-box
        .item-name
          .item-name__title
            商品名
          .item-name__need
            必須
        .item-nbox
          = form.text_field :name, class: 'item-nbox__form', :placeholder => '40文字以内'
        .item-details
          .item-details__name
            商品の説明
          .item-details__need
            必須
        .item-dbox
          = form.text_area :info, class: 'item-dbox__form', :placeholder => '商品の説明(必須1,000文字以内）（色、素材、重さ、定価、注意点）例）2010年頃に１万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。'
        .text-count
          0/1000
      .item-type-box
        .type-text
          商品の詳細
        .category
          .category__title
            カテゴリー
          .category__need
            必須
        .product_category-select
          = form.select :category, @category_parent_array, {selected: @parent_category.name}, {class: "category_select-box", id: "category_select"}
        #children_wrapper.product_select-children
          = form.select :category, options_for_select(@category_children_array.map{|e| [e.name, e.id, {data:{category: e.id}}]},{selected: @child_category.id}), {prompt: "選択してください"}, {class: "category_select-box", id: "child_category"}
        #grandchildren_wrapper.product_select-grandchildren
          = form.select :category, options_for_select(@category_grandchildren_array.map{|o| [o.name, o.id, {data:{category: o.id}}]},{selected: @grandchild_category.id}), {prompt: "選択してください"}, {class: "category_select-box", id: "grandchild_category"}

        .brand
          .brand__title
            ブランド
          .brand__need
            任意
        .item-bbox
          = form.text_field :brand, class: 'item-bbox__form', :placeholder => '例）シャネル'
        .status
          .status__title
            商品の状態
          .status__need
            必須
        .item-sbox
          = form.collection_select :condition_id, Condition.all, :id, :name
      .item-deliver-box
        .deliver-text
          配送について
        .deliver-fee
          .deliver-fee__title
            配送料の負担
          .deliver-fee__need
            必須
        .item-dvbox
          = form.collection_select :deliverypays_id , Deliverypays.all, :id, :name
        .deliver-area
          .deliver-area__title
            配送料場所
          .deliver-area__need
            必須
        .item-abox
          = form.collection_select :prefecture_id, Prefecture.all, :id, :name
        .deliver-date
          .deliver-date__title
            配送までの日数
          .deliver-date__need
            必須
        .item-datebox
          = form.collection_select :deliverydate_id , Deliverydate.all, :id, :name
      .item-sell-box
        .price-text
          価格（¥300〜9,999,999）
        .sell-prices
          .sell-price
            .sell-price__title
              販売価格
            .sell-price__need
              必須
          .sell-box
            .sell-box__text
              ¥
            = form.number_field :price, class: 'sell-box__form', :placeholder => '０', min: 300, max: 9999999
        .sell-margin
          .sell-margin__text
            販売手数料 (10%)
          .sell-margin__stick
            ー
        %hr.is-border
        .sell-benefit
          .sell-margin__text
            販売履歴
          .sell-margin__stick
            ー
      = form.submit "更新する" , class: 'sell-btn'
      .return-btn
        = link_to root_path, class: "return-btn__return" do
          .return-btn__text
            もどる
      .bottom-text
        禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。また、出品をもちまして加盟店規約に同意したことになります。
    = render "more/footer"

app/views/items/index.html.haml
.t-headers
  .t-header
    .t-header__main
      .t-header__main__img
        = link_to root_path do
          =image_tag'logo.png', size: "140x40", class: "img"
      .t-header__main__box
        = form_with(url: search_items_path, local: true, method: :get, class: "s-form") do |form| 
          = form.text_field :keyword, placeholder: "キーワードから探す", class: "s-form__text" 
          %label.s-label
            %i.fa.fa-search
              = form.submit class: "s-btn" 
    .t-header__nav
      %ul.t-header__nav__left
        %li.t-header__nav__left--item
          = link_to category_items_path do
            カテゴリー
        %li.t-header__nav__left--item
          = link_to "#" do
            ブランド
      %ul.t-header__nav__right
        - if user_signed_in?
          %li.t-header__nav__right--item2
            = link_to user_path(current_user.id), class: "a" do
              マイページ
        - else
          %li.t-header__nav__right--item2
            = link_to new_user_session_path, class: "a" do
              ログイン
          %li.t-header__nav__right--item2
            = link_to new_user_registration_path,class: "a" do
              新規会員登録
.t-contents
  .t-content
    .t-content__box
      .t-content__box__title
        %br
        %h2 人生を変えるフリマアプリ
      .t-content__box__text
        %p emaはだれでもかんたんに出品・購入できる
        %p フリマアプリです
      .t-content__box__btn
        = link_to "https://www.apple.com/jp/ios/app-store/" do
          =image_tag"appstore-logo.png",size:"180x53",class:"logo"
        = link_to "https://play.google.com/store?hl=ja" do
          =image_tag"Google-Play-png.png",size:"180x53",class:"logo"
          
  .t-content1
    %h2.t-content1__title
      EMAが選ばれる３つの理由
    %h2.t-content1__line
    %ul.t-content1__lists
      %li.t-content1__lists__list
        %span.number
          1
        = image_tag"pict-reason-01.jpg",size: "262x262",class:"img1"
        .t-content1__lists__list__text
          %span
            3分
          ですぐに出品
        .t-content1__lists__list__title
          スマホで入力するだけで
          %br
          簡単に出品できる！
      %li.t-content1__lists__list
        %span.number
          2
        = image_tag"pict-reason-02.jpg",size: "262x262",class:"img2"
        .t-content1__lists__list__text
          %span
            シンプル
          で使いやすい
        .t-content1__lists__list__title
          めんどくさい入力は必要なく、
          %br
          検索も購入もスムーズ！
      %li.t-content1__lists__list
        %span.number
          3
        = image_tag"pict-reason-03.jpg",size: "262x262",class:"img3"
        .t-content1__lists__list__text
          手数料
          %span
            業界最安
        .t-content1__lists__list__title
          最大3%でお得に出品&購入！

  .t-content3
    .t-content3__box
      .t-content3__box__title
        %a 会員数日本一位
      .t-content3__box__text
        %a FURIMAは、フリマアプリで最も人気。
        %br
        %a 出品・購入回数も業界最多です！
        %br
        %a ほしかったあの商品に出会えるかもしれません。
      .t-content3__box__icon
        = link_to "https://www.apple.com/jp/ios/app-store/" do
          =image_tag"appstore-logo.png",size:"180x53",class:"logo"
        = link_to "https://play.google.com/store?hl=ja" do
          =image_tag"Google-Play-png.png",size:"180x53",class:"logo"
  .t-content2
    .t-content2__title
      EMAの特徴
    %h2.t-content2__line
    .t-content2__lists
      .t-content2__lists__list
        = image_tag"icon-01.png",size: "138x213",class:"t-content2__lists__list--img"
        .t-content2__lists__list__title
          簡単に売り買いできる
        .t-content2__lists__list__text
          スマホひとつで、いつで
          %br
          もどこでも簡単に出品・
          %br
          購入が可能！
      .t-content2__lists__list
        = image_tag"icon-02.svg",size: "138x213",class:"t-content2__lists__list--img"
        .t-content2__lists__list__title
          売上金は即日振込みに
          %br
          対応
        .t-content2__lists__list__text
          午前9時までに振込を依頼
          %br
          いただければ、翌日に指
          %br
          定の口座に入金いたしま
          %br
          す!
      .t-content2__lists__list
        = image_tag"icon-04.png",size: "138x213",class:"t-content2__lists__list--img"
        .t-content2__lists__list__title
          様々な支払いに対応
        .t-content2__lists__list__text
          お支払いは、クレジット
          %br
          カードだけでなく、ポイ
          %br
          ントや売上金など多彩な
          %br
          方法があります。
  
  .t-content4
    .t-content4__title
      ピックアップカテゴリー
    .t-content4__box
      .t-content4__box__text
        = link_to "#" do
          新規投稿商品
      .t-content4__box__lists
        - @items.each do |item|
          .t-content4__box__lists__list
            = link_to item_path(item.id),data: {"turbolinks" => false} do
              .t-content4__box__lists__list__img
                = image_tag item.images.first.src.url,size:"220x150"
                -if item.buyer_id.present?
                  .items-box_photo__sold
                    .items-box_photo__sold__inner
                      %a SOLD
              .t-content4__box__lists__list__box
                .t-content4__box__lists__list__box--name
                  %a 
                    = item.name
                .t-content4__box__lists__list__box__deta
                  %a 
                    ¥
                    = item.price
                  = icon("fa","star", class: "star")
                  = item.favorites.count
                  %p (税込)
  .t-content5
    .t-content5__title
      ピックアップブランド
    .t-content5__box
      .t-content5__box__name
        = link_to "#" do
          アーカイバ
      .t-content5__box__lists
        - @items.each do |item|
          .t-content5__box__lists__list
            = link_to item_path(item.id),data: {"turbolinks" => false} do
              .t-content5__box__lists__list__img
                = image_tag item.images.first.src.url,size:"220x150"
                -if item.buyer_id.present?
                  .items-box_photo__sold
                    .items-box_photo__sold__inner
                      %a SOLD
              .t-content5__box__lists__list__box
                .t-content5__box__lists__list__box--name
                  %a 
                    = item.name
                .t-content5__box__lists__list__box__deta
                  %a 
                    ¥
                    = item.price
                  = icon("fa","star", class: "star")
                  = item.favorites.count
                  %p (税込)
.t-contents1
  .t-contents1__box
    %h2.t-contents1__box__title
      だれでも、かんたん、人生を変えるフリマアプリ
    %p.t-contents1__box__text
      今すぐ無料ダウンロード！
    .t-contents1__box__imag
      = link_to "https://www.apple.com/jp/ios/app-store/" do
        =image_tag"appstore-logo.png",size:"180x53",class:"logo"
      = link_to "https://play.google.com/store?hl=ja" do
        =image_tag"Google-Play-png.png",size:"180x53",class:"logo"
.t-footers
  %ul.t-footers__contents
    %li.t-footers__contents__content
      %h2.t-footers__contents__content__title
        EMAについて
      %ul 
        %li
          %a 会社概要(運営会社)
        %li
          %a プライバシーポリシー
        %li
          %a FURIMA利用規約
        %li
          %a ポイントに関する特約
    %li.t-footers__contents__content
      %h2.t-footers__contents__content__title
        FURIMAを見る
      %ul 
        %li
          %a カテゴリー一覧
        %li
          %a ブランド一覧
        %li
    %li.t-footers__contents__content
      %h2.t-footers__contents__content__title
        ヘルプ＆ガイド
      %ul 
        %li
          %a FURIMAガイド
        %li
          %a FURIMAロゴ利用ガイドライン
        %li
          %a お知らせ
  .t-footers__logo
    = link_to root_path do
      = image_tag"logo-white.png",size:"140x46",class:"eee"
  %p © EMA 
- if user_signed_in?
  = render "more/put"

app/views/items/search.html.haml
.t-headers
  .t-header
    .t-header__main
      .t-header__main__img
        = link_to root_path do
          =image_tag'logo.png', size: "140x40", class: "img"
      .t-header__main__box
        = form_with(url: search_items_path, local: true, method: :get, class: "s-form") do |form| 
          = form.text_field :keyword, placeholder: "キーワードから探す", class: "s-form__text" 
          %label.s-label
            %i.fa.fa-search
              = form.submit class: "s-btn" 
    .t-header__nav
      %ul.t-header__nav__left
        %li.t-header__nav__left--item
          = link_to category_items_path do
            カテゴリー
        %li.t-header__nav__left--item
          = link_to "#" do
            ブランド
      %ul.t-header__nav__right
        - if user_signed_in?
          %li.t-header__nav__right--item2
            = link_to user_path(current_user.id), class: "a" do
              マイページ
        - else
          %li.t-header__nav__right--item2
            = link_to new_user_session_path, class: "a" do
              ログイン
          %li.t-header__nav__right--item2
            = link_to new_user_registration_path,class: "a" do
              新規会員登録
.s-content
  .s-main
    .s-main__box
      - @items.each do |item|
        .s-main__box--list
          = link_to item_path(item.id) do
            .t-content5__box__lists__list__img
              = image_tag item.images.first.src.url,size:"220x150"
              -if item.buyer_id.present?
                .items-box_photo__sold
                  .items-box_photo__sold__inner
                    %a SOLD
            .t-content5__box__lists__list__box
              .t-content5__box__lists__list__box--name
                %a 
                  = item.name
              .t-content5__box__lists__list__box__deta
                %a 
                  ¥
                  = item.price
                = icon("fa","star", class: "star")
                0
                %p (税込)
    .s-page
      = paginate(@items)
  = render "more/footer"

app/views/items/show.html.haml
.t-headers
  .t-header
    .t-header__main
      .t-header__main__img
        = link_to root_path do
          =image_tag'logo.png', size: "140x40", class: "img"
      .t-header__main__box
        = form_with(url: search_items_path, local: true, method: :get, class: "s-form") do |form| 
          = form.text_field :keyword, placeholder: "キーワードから探す", class: "s-form__text" 
          %label.s-label
            %i.fa.fa-search
              = form.submit class: "s-btn" 
    .t-header__nav
      %ul.t-header__nav__left
        %li.t-header__nav__left--item
          = link_to "#" do
            カテゴリー
        %li.t-header__nav__left--item
          = link_to "#" do
            ブランド
      %ul.t-header__nav__right
        - if user_signed_in?
          %li.t-header__nav__right--item2
            = link_to user_path(current_user.id), class: "a" do
              マイページ
        - else
          %li.t-header__nav__right--item2
            = link_to new_user_session_path, class: "a" do
              ログイン
          %li.t-header__nav__right--item2
            = link_to new_user_registration_path,class: "a" do
              新規会員登録
  .main
    .show-main
      .content
        .content__top
          .item-box
            .item-box__name
              = @item.name
            .item-box__photo
              %span
                = image_tag @item.images.first.src.url,size:"620x443"
                - if @item.images
                  %ul
                    - @item.images.each do |image|
                      %li
                        = image_tag image.src.url,size:"140x97"
            .item-box__price
              ¥
              = @item.price
              .item-box__price__detail
                %span
                  (税込)
                %span
                  送料込み
            .tablebox-title
            .info-table 
              = @item.info
              %table
                %tbody
                  %tr
                    %th
                      出品者
                    %td
                      = link_to do
                        = @item.user.name
                  %tr
                    %th
                      カテゴリー
                    %td
                      = link_to do
                        =@parent.name
                      %br
                      = link_to do
                        =@child.name
                      %br
                      = link_to do
                        =@grandchild.name
                  %tr
                    %th
                      ブランド
                    %td
                  %tr
                    %th
                      商品の状態
                    %td
                      = link_to do
                        =@condition.name
                  %tr
                    %th
                      配送料の負担	
                    %td
                      = link_to do
                        =@deliverypays.name
                  %tr
                    %th
                      発送元の地域
                    %td
                      = link_to do
                        =@prefecture.name
                  %tr
                    %th
                      発送日の目安	
                    %td
                      = link_to do
                        =@deliverydate.name
            .favorite
              %i.fa.fa-star
                = render "more/favorite"
            .buy-box
              .delete-box__btn
                - if user_signed_in? && current_user.id == @item.user_id
                  - if @item.buyer_id.present?
                    = link_to item_path(@item.id), method: :delete do
                      %button#delete-btn 
                        削除する
                  - else
                    .box-btn
                      = link_to edit_item_path(@item.id) do
                        %button#edit-btn
                          編集する
                      = link_to item_path(@item.id), method: :delete do
                        %button#delete-btn-new
                          削除する
                -elsif user_signed_in?
                  -if @item.buyer_id.present?
                  - else
                    .buy-box__btn
                      = link_to confirm_item_path,data: {"turbolinks" => false} do
                        %button#buy-btn 
                          購入する
                - else
                  .buy-box__btn
                    = link_to new_user_registration_path,data: {"turbolinks" => false} do
                      %button#buy-btn 
                        購入する
          .comment-box
            - if current_user
              = form_with(model: [@item, @comment], local: true, id: "new_comment") do |form|
                = form.text_area :text, placeholder: "コメントする", rows: "2",class: "textbox"
                .comment-box__message
                  相手のことを考え丁寧なコメントを心がけましょう。
                  %br
                  不快な言葉遣いなどは利用制限や退会処分となることがあります。
                .comment-box__btn
                  = form.submit "コメントする",id:"comment-btn",class:"form__submit"
            - else
              .comment-dekimasen
                コメントするには
                = link_to user_session_path do
                  ログイン
              .commento-dekimasen2 
                してください。
          .commentss
            %a コメント一覧
            .comments
              .comment
                - if @comments
                  - @comments.each do |comment|
                    .comment__box
                      .comment__box__user
                        = comment.user.name
                      .comment__box__text
                        = comment.text 
        .link-page
          .link-page__left
            = link_to "#" do
              %i.fa.fa-angle-left
              前の商品
          .link-page__right
            = link_to "#" do
              後ろの商品
              %i.fa.fa-angle-right
              
        .look-item
          = link_to "#" do
            レディースをもっと見る

.t-contents1
  .t-contents1__box
    %h2.t-contents1__box__title
      だれでも、かんたん、人生を変えるフリマアプリ
    %p.t-contents1__box__text
      今すぐ無料ダウンロード！
    .t-contents1__box__imag
      = link_to "https://www.apple.com/jp/ios/app-store/" do
        =image_tag"appstore-logo.png",size:"180x53",class:"logo"
      = link_to "https://play.google.com/store?hl=ja" do
        =image_tag"Google-Play-png.png",size:"180x53",class:"logo"
.t-footers
  %ul.t-footers__contents
    %li.t-footers__contents__content
      %h2.t-footers__contents__content__title
        EMAについて
      %ul 
        %li
          %a 会社概要(運営会社)
        %li
          %a プライバシーポリシー
        %li
          %a FURIMA利用規約
        %li
          %a ポイントに関する特約
    %li.t-footers__contents__content
      %h2.t-footers__contents__content__title
        FURIMAを見る
      %ul 
        %li
          %a カテゴリー一覧
        %li
          %a ブランド一覧
        %li
    %li.t-footers__contents__content
      %h2.t-footers__contents__content__title
        ヘルプ＆ガイド
      %ul 
        %li
          %a FURIMAガイド
        %li
          %a FURIMAロゴ利用ガイドライン
        %li
          %a お知らせ
  .t-footers__logo
    = link_to root_path do
      = image_tag"logo-white.png",size:"140x46",class:"eee"
  %p © EMA