config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items do
    
    resources :favorites, only: [:create,:destroy]
    resources :comments, only: :create
    member do
      get 'confirm', to: 'items#confirm'
      post 'pay', to: 'items#pay'
      get 'done', to: 'items#done'
    end
    collection do
      get 'category_children'
      get 'category_grandchildren'
      get 'category'
    end
    collection do
      get 'search'
    end
  end
  resources :users, only: :show 
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card

  require "payjp"

  def new
    redirect_to action: "show" if @card
  end

  def pay 
    Payjp.api_key = Rails.application.credentials.PAYJP[:PAYJP_PRIVATE_KEY]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', 
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    unless @card.blank?
      Payjp.api_key =Rails.application.credentials.PAYJP[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete 
      @card.delete 
    end
      redirect_to action: "new"
  end

  def show
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.PAYJP[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def set_card
    @card = Card.where(user_id: current_user.id).first
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
.o-contents
  = render "more/header"
  .c-main
    .c-main__box
      .c-main__box--text
        支払い方法
      = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm",class: "c-form") do
        .c-form__content
          .c-form__content--group
            %label カード番号
            = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            =image_tag'card-1.gif', size: "343x30"
          .c-form__content--date
            %label 有効期限
            .c-limit
              %select#exp_month{name: "exp_month", type: "text"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %span 月
              %select#exp_year{name: "exp_year", type: "text"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %span 年
          .c-form__content--code
            %label セキュリティコード
            = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
          #card_token
            = submit_tag "登録する", id: "token_submit"
  = render "more/footer"

app/views/card/show.html.haml
.o-contents
  = render "more/header"
  .cs-main
    .cs-main__box
      .cs-main__box--text
        登録クレジットカード情報
      .cs-main__box--data
        .cs-number
          = "**** **** **** " + @default_card_information.last4
        .cs-date
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
      = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
        %input{ type: "hidden", name: "card_id", value: "" }
        %button 削除する
  = render "more/footer"